version: '3.7'

services:

    wikipedia_server:
        build: .
        container_name: wikipedia_server
        restart: unless-stopped
        ports:
            - 127.0.0.1:9095:9095
        volumes:
            - $DUMP_PATH:/dump
            # - ./static:/static
