version: '3.7'

services:

    wikipedia_server:
        build: .
        container_name: wikipedia_server
        restart: unless-stopped
        ports:
            - 9095:9095
        environment:
            - DUMP_PATH=/dump
        volumes:
            - $DUMP_PATH:/dump
