version: '3.7'

services:

    wikipedia_server:
        build: .
        container_name: wikipedia_server
        restart: unless-stopped
        ports:
            - 9095:9095
        volumes:
            - .:/app

    redis:
        image: redis/redis-stack:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
            - 9096:8001
